# Generated by Django 2.2.16 on 2022-05-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_and_comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
    ]
