# Generated by Django 2.2.16 on 2022-05-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_and_comments', '0002_auto_20220501_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
    ]
