# Generated by Django 2.2.16 on 2022-05-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_and_comments', '0003_auto_20220502_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
    ]
