# Generated by Django 2.2.16 on 2022-04-28 09:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('reviews', '0003_auto_20220428_0147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cathegory',
            new_name='Category',
        ),
    ]
