# Generated by Django 2.2.16 on 2022-04-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220428_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='cathegory',
            new_name='category',
        ),
    ]
