# Generated by Django 2.2.16 on 2022-04-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220428_1307'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='unique_title',
        ),
    ]
