# Generated by Django 2.2.16 on 2022-05-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220501_2110'),
        ('reviews', '0007_auto_20220430_2343'),
    ]

    operations = [
    ]
