# Generated by Django 2.2.16 on 2022-05-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20220501_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
